### ISSUE TITLE
Forked your neat extension looking to merge and kill fork

### ISSUE THREAD

**Issue by nmccready** [apihlaja/lazy-debug#1]
@apihlaja I forked your repo in an emergency to quickly support node 0.X (removing es6).

I can PR [this](https://github.com/apihlaja/lazy-debug/compare/master...nmccready:lazy-debug-legacy) with the removal of the version bumps, and package renaming. 

If your totally opposed then I will just continue as is.

**Comment by apihlaja** [comment]
PR welcome.. Looks good to me generally.

https://github.com/apihlaja/lazy-debug/compare/master...nmccready:lazy-debug-legacy#diff-d25ceb1291a5ff8440de015502c0922eL77 (ie. `/web\\browser.jsx` -> `/web/browser.jsx`)

Not sure what this indicates, kind of hints there is an issue somewhere.

The reason for some odd looking paths is browserify bug: https://github.com/substack/insert-module-globals/pull/63

**Comment by nmccready** [comment]
closing since #2
